---
abstract: Interface to the W3C CSS Validator
author:
  - 'Bjoern Hoehrmann <bjoern@hoehrmann.de>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: WebService-Validator-CSS-W3C
no_index:
  directory:
    - t
    - inc
requires:
  Carp: 0
  Class::Accessor: 0
  LWP::UserAgent: 0
  SOAP::Lite: 0.65
  URI: 0
  URI::QueryParam: 0
version: 0.3
